### PR TITLE
Fix #223 prevent-refresh

### LINKED ISSUE #223: Fix `prevent-refresh` — 0 seconds delay content
Steps to reproduce
1. Add these rules:
```
example.org#%#//scriptlet('prevent-refresh')
||example.org^$replace=/<style type/<meta http-equiv="refresh" content="0; url=https:\/\/google.com\/"><style type/
```
2. Go to - https://example.org/

Redirection to `google.com` should be blocked by `prevent-refresh` scriptlet, but it seems that it doesn't work due to `content="0;`
Probably problem is in this line:
https://github.com/AdguardTeam/Scriptlets/blob/fdef488c1f529ce85f87d441eafbf0422b3d8336/src/scriptlets/prevent-refresh.js#L91-L93

Value of `secondsToRun` is `0`, so condition is true, returns here and redirection is not aborted.

### PR DESCRIPTION
**Pull request by AdamWr**
Issue - https://github.com/AdguardTeam/Scriptlets/issues/223

Fixes issue with not working scriptlet if "content" has 0 seconds delay (changed `!secondsToRun` to `secondsToRun == null`).

I have added also:
```js
if (!delays.length) { return; }
```
to `getMetaContentDelay` function to fix error - `TypeError: Reduce of empty array with no initial value`, in case if there is invalid meta's content. This error is visible only in console as scriptlets run in `try...catch`, but I thought that it may be worth to fix.

Added `removeMeta` function, to remove `meta` element when test is done.

Modified `REL_PAGE_PATH` to fix issue error `'../scriptlets/test-files/empty.html' causes ENOENT: no such file or directory` when redirection is not prevented after running `yarn test`.

### CODE REVIEW

File: src/scriptlets/prevent-refresh.js [hunk 1]
```diff
@@ -71,6 +71,9 @@ export function preventRefresh(source, delaySec) {
                 return contentDelay;
             })
             .filter((delay) => delay !== null);
+        // Check if "delays" array is empty, may happens when meta's content is invalid
+        // and reduce() method cannot be used with empty arrays without initial value
+        if (!delays.length) { return; }
```
Comment (slavaleleka) [inline src/scriptlets/prevent-refresh.js:76]: we do not use one-line return statement, better
```
if (!delays.length) {
    return;
}
```

File: src/scriptlets/prevent-refresh.js [hunk 2]
```diff
@@ -84,11 +87,11 @@ export function preventRefresh(source, delaySec) {
         }
         let secondsToRun = getNumberFromString(delaySec);
         // Check if argument is provided
-        if (!secondsToRun) {
+        if (secondsToRun == null) {
```
Comment (slavaleleka) [inline src/scriptlets/prevent-refresh.js:90]: Strict equality `===` should be used instead of just `==`. and if you need to check whether the `secondsToRun` is defined, the condition can be updated to 
```
if (typeof secondsToRun !== 'undefined') { ... }
```

File: src/scriptlets/prevent-refresh.js (hunk 1 above)
Comment (slavaleleka) [reply src/scriptlets/prevent-refresh.js:76]: OR 
you can obviously return `null` here and check it by strict equality after it
https://github.com/AdguardTeam/Scriptlets/pull/238/files#diff-4b774935780fa37cb477fd62f4db8198f3d8d0447b0fc2824e1b7bb13d349201R94

**Review by slavaleleka — CHANGES_REQUESTED** [review]

File: tests/scriptlets/prevent-refresh.test.js [hunk 3]
```diff
@@ -65,6 +85,37 @@ test('Prevent redirect, delay from arg', (assert) => {
...
+            apply: wrapperLog,
+        };
+        window.console.log = new Proxy(window.console.log, handlerLog);
+    };
+    checkConsole();
+    runScriptlet(name);
+    const done = assert.async();
+    setTimeout(() => {
+        assert.ok(testPassed, 'No error');
+        removeMeta();
```
Comment (slavaleleka) [inline tests/scriptlets/prevent-refresh.test.js:118]: could you please add checking for `hit`? it should be `undefined` for this test, right?

File: src/scriptlets/prevent-refresh.js (hunk 1 above)
Comment (AdamWr) [reply src/scriptlets/prevent-refresh.js]: Okay, I have changed it as requested.

File: src/scriptlets/prevent-refresh.js (hunk 2 above)
Comment (AdamWr) [reply src/scriptlets/prevent-refresh.js]: Done.
I didn't use strict equality, because I thought that there may be situation where `secondsToRun` can be `undefined` and in another case when it can be `null`, but it seems that I was wrong.

File: tests/scriptlets/prevent-refresh.test.js (hunk 3 above)
Comment (AdamWr) [reply tests/scriptlets/prevent-refresh.test.js:119]: Done.
