### PR TITLE
Fix #226 abort-on-stack-trace

### LINKED ISSUE #226: Fix `abort-on-stack-trace` — maximum call stack size exceeded
Steps to reproduce
1. Add this rule:
```
fiddle.jshell.net#%#//scriptlet('abort-on-stack-trace', 'RegExp', 'qwertyuiopasdfg')
```
2. Go to - https://jsfiddle.net/67u801am/

<details><summary>Code</summary>

```js
<script>
let re = new RegExp('ab+c', 'i')
console.log(re);
</script>
```

</details>

Mentioned rule causes `RangeError: Maximum call stack size exceeded`.
<details><summary>Screenshot</summary>

image

</details>

I guess that it rather shouldn't happens.

### PR DESCRIPTION
**Pull request by AdamWr**
Fixes issue with `RangeError: Maximum call stack size exceeded` in `abort-on-stack-trace` - https://github.com/AdguardTeam/Scriptlets/issues/226

### CODE REVIEW

File: src/helpers/match-stack.js [hunk 1]
```diff
@@ -7,7 +7,18 @@ import { toRegExp } from './string-utils';
  * @param {string} stackTrace - script error stack trace
  * @returns {boolean}
  */
+// https://github.com/AdguardTeam/Scriptlets/issues/226
+// eslint-disable-next-line import/no-mutable-exports, func-names
+export let shouldAbortStack = function () { };
```
Comment (slavaleleka) [inline src/helpers/match-stack.js:12]: why as a function? 

just `export let shouldAbortStack = false;` seems to work fine. and no eslint exception needed above

Comment (slavaleleka) [reply src/helpers/match-stack.js:12]: and move it please before jsdoc comment related to `matchStackTrace`

File: src/scriptlets/abort-on-stack-trace.js [hunk 2]
```diff
@@ -47,6 +49,10 @@ export function abortOnStackTrace(source, property, stack) {
         return;
     }
 
+    // https://github.com/AdguardTeam/Scriptlets/issues/226
+    // sets shouldAbortStack to true
```
Comment (slavaleleka) [inline src/scriptlets/abort-on-stack-trace.js:53]: describing part should be before the additional issue link

**Review by slavaleleka — CHANGES_REQUESTED** [review]

File: src/helpers/match-stack.js (hunk 1 above)
Comment (AdamWr) [reply src/helpers/match-stack.js:12]: > why as a function?
> 
> just `export let shouldAbortStack = false;` seems to work fine. and no eslint exception needed above

I wanted to use it as a variable, but when it's not used as a function, then it's removed from script when script is compiled/builded, and then it's exposed in a global scope. So that's why I used this as a function.
Similar issue occurs with something like this:
```
export let someObject = {};
```
but in this case, build fails.
<details><summary>Screenshot</summary>

image

</details>

Maybe I'm doing something wrong, so I would appreciate any tips/helps with this.

Comment (slavaleleka) [reply src/helpers/match-stack.js:5]: you're right, it should be a function type
